# This file contains steps for running the public OSS pipeline.  It defines
# steps required by the public build specifically, then includes the pipeline
# file containing common build steps.

# Non-buildkite nodes to re-use:
common_values:
  retry: &retry_on_agent_kill
    automatic: &agent_kill_conditions
      - exit_status: -1  # Agent was lost
        limit: 2
      - exit_status: 255 # Forced agent shutdown
        limit: 2

steps:
  # TODO: ronh: decide what kind of linting we want in the OSS pipeline
  # - label: ':git: Lint commits'
  #   key: lint-commits
  #   branches: '!refs/heads/main'
  #   commands:
  #     - ./scripts/commit_lint.sh
  #   agents:
  #     queue: t3a-small

  - label: ':docker: Build build image'
    key: build-image
    commands:
      - '.buildkite/build-image.sh build/Dockerfile readyset-build .'
    plugins:
      ecr#v2.5.0:
        login: true
        retries: 3
    retry: *retry_on_agent_kill

  - label: ':docker: Build cargo-deny image'
    key: cargo-deny-image
    commands:
      - '.buildkite/build-image.sh build/Dockerfile.cargo-deny cargo-deny .'
    env:
      VERSION: "${BUILDKITE_COMMIT}"
    plugins:
      ecr#v2.5.0:
        login: true
        retries: 3
    retry: *retry_on_agent_kill

  - label: ':pipeline: Upload public-common pipeline'
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline.public-common.yml
    agents:
      queue: t3a-small
