[package]
name = "replicators"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { workspace = true, features = ["derive","env"] }
native-tls = "0.2.7"
tokio = { workspace = true, features = ["full"] }
futures = { version = "0.3" }
fail = "0.5.0"
bytes = "1.0"
chrono = "0.4"
itertools = "0.10"
metrics = "0.21"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2.5"
serde_json = { version = "1", features = ["arbitrary_precision"] }
hex = "0.4.3"
rust_decimal = { version = "1.26" }
bit-vec = { version = "0.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
nom_locate = "4.0.0"

tokio-postgres = { workspace = true, features = ["with-chrono-0_4", "with-serde_json-1"] }
postgres-types = { workspace = true, features = ["with-chrono-0_4", "with-serde_json-1"] }
postgres-native-tls = { workspace = true }
postgres-protocol = { workspace = true }
mysql_async = { workspace = true }

readyset-vitess-data = { path = "../readyset-vitess-data" }
vitess-grpc = "0.1.2"
tonic = { version = "0.9", features = ["tls"] }

mysql_common = "0.29.2"
nom-sql = { path = "../nom-sql" }
readyset-client = { path = "../readyset-client" }
readyset-errors = { path = "../readyset-errors" }
readyset-util = { path = "../readyset-util" }
readyset-tracing = { path = "../readyset-tracing" }
mysql-time = { path = "../mysql-time" }
readyset-data = { path = "../readyset-data" }
database-utils = { path = "../database-utils" }
test-utils = { path = "../test-utils" }
failpoint-macros = { path = "../failpoint-macros" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
deadpool-postgres = "0.10.3"

[dev-dependencies]
readyset-server = { path = "../readyset-server" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter", features = ["test-util"] }
readyset-client-test-helpers = { path = "../readyset-client-test-helpers", features = ["postgres"] }
proptest-stateful = { path = "../proptest-stateful" }
serial_test = "0.5"
rand = "0.8.5"
proptest = "1.0.0"
test-strategy = "0.2.0"

[features]
ddl_vertical_tests = []
failure_injection = ["fail/failpoints", "nom-sql/failure_injection", "readyset-client/failure_injection"]
